### ISSUE TITLE
Feature Request: Add Serde Feature Flag

### ISSUE THREAD

**Issue by askandera** [ambuc/quadtree#11]
It would super convenient to be able to serialize and deserialize quadtrees. I've already implemented this change locally, and am happy to open a PR, but I can't seem to push a branch. I signed the Google Open Source contrib thing, and read through the contributing page, but I can't seem to push my branch to open a PR from it.

**Comment by ambuc** [comment]
Sorry to hear that — AFAIK, signing or not signing the OSS contributor agreement should gate my ability to merge code with an unverified author, not gate your ability to open a PR. Maybe I can help debug your issue pushing the branch, what’s going on?

**Comment by askandera** [comment]
I figure out the issue. Will open a PR in a couple minutes.

**Comment by askandera** [comment]
https://github.com/ambuc/quadtree/pull/12

So sorry about the initial issue. I didn't quite understand I had to fork as opposed to just making a branch and pushing it.
