### ISSUE TITLE
Noob question regarding region sizes

### ISSUE THREAD

**Issue by quantumpotato** [ambuc/quadtree#14]
Hi, please forgive my naivety here, I am new to Rust & quadtrees.

If I understand your docs correctly, the shape of the space must start at 0,0. So, using bevy engine which uses a graphing coordinate system where -,- is bottom left of screen, I just need to translate that so that -,. is 0,0 in your system. That seems fine.

I'm going to have regular polygonal objects moving across the entire screen space. (Think: A circle or a square). Should I use the sizes for those as pixel sizes, and the total size of the Tree space as the entire range of the window pixel size?

The examples you gave, which are thoughtful, use relatively low numbers (going up to 4,4) compared to what a full screen will use.

Or is the idea that I should start with 4,4 mapping to the full screen width and the library subdivides from there?

**Comment by ambuc** [comment]
Hi, thanks for your question. 

As you noted, the library can only subdivide down to a unit of one. So if you know your total canvas needs to be, say, 1920x1080, you probably want to round the larger value up to the nearest power of two ($2^{11} = 2048$) for a depth of 11. 

Quadtrees are good for storing objects and detecting collisions. But I don't know how effectively they perform as a backing store for windows or pixels, much less for real-time graphics for gameplay.

I don't know a ton about Bevy, but I found these examples ([1](https://github.com/Lommix/boids-quadtree-rs), [2](https://github.com/tandalesc/bevy_boids/tree/main)) which might answer your question by way of example better than I can.

**Comment by quantumpotato** [comment]
Thank you!
